config/routes.rb
DssScheduler::Application.routes.draw do
  resources :resources do
    resources :questions
  end
  match '/reservations/wizard', :controller => 'reservations', :action => 'wizard'
  resources :reservations
  resources :resource_categories
  
  get '/admin', :controller => "admin", :action=> "index"
  get '/welcome', :controller => "application", :action => "welcome"
  get '/logout', :controller => "application", :action => "logout"
  root :to => 'application#welcome'
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :title, :cache_end_time, :cache_start_time, :exchange_event_id, :exchange_change_key, :package_id, :person_id, :questionnaire_response_id, :recurrence_id, :resource_id, :resource_attributes
  attr_writer :current_step
  
  # validates :person_id, :resource_id, :cache_start_time, :cache_end_time, :presence => true
  validates :resource_id, :presence => true, :if => lambda { |o| o.current_step == "step2" }
  
  belongs_to :resource
  belongs_to :person
  has_many :questions
  accepts_nested_attributes_for :resource
  
  
  def current_step
    @current_step || steps.first
  end
  
  def steps
    %w[step1 step2 step3 step4]
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end

  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.person_id.to_s,
      :description => self.exchange_event_id,
      :start => self.cache_start_time,
      :end => self.cache_end_time,
      :allDay => false,
      :recurring => false,
      :url => Rails.application.routes.url_helpers.reservation_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_filter :init_wizard_session, :only => [:index, :wizard, :new]

  # GET /reservations
  # GET /reservations.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new
    
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @person = Person.find_by_uid(1) #TODO: Change the 0 to the current user UID after implementing the Roles Mgmt
    @reservations = @person.reservations
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
  
  def init_wizard_session
    #debugger
    #session[:reservation_step] = session[:reservation_params] = nil

    session[:reservation_params] ||= {}
    session[:reservation_params].deep_merge!(params[:reservation]) if params[:reservation]
    @reservation = Reservation.new(session[:reservation_params])
    session[:resource_params] ||= {}
    session[:resource_params].deep_merge!(params[:resource]) if params[:resource]
    session[:question_response_params] ||= {}
    session[:question_response_params].deep_merge!(params[:question_response]) if params[:question_response]
    
    @reservation.current_step = session[:reservation_step]
    @person = Person.find_by_uid(1) #TODO: Change the 1 to the current user UID after implementing the Roles Mgmt
    @reservations = @person.reservations
    @resource_categories = ResourceCategory.all

    # We can have a switch-case statement here to get the variables depending on the step #
    @departments = Resource.select("DISTINCT(ou_uid), description") 
    @resource = @reservation.resource
    @resource_category = @resource.resource_category if @resource
    @resources = @resource_category.resources if @resource_category
    @questions = @resource.questions if @resource
    @questions.each do |q|
        response = q.question_responses.build
    end if (@questions && !response)
  end
  
  def wizard
    #debugger
    
    if params[:back_button]
      @reservation.previous_step
      session[:reservation_step] = @reservation.current_step
    else
      if @reservation.last_step?
        @reservation.save if @reservation.all_valid?
      else
        @reservation.next_step
      end
      session[:reservation_step] = @reservation.current_step
    end
    if @reservation.new_record?
      respond_to do |format|
        format.html # show.html.erb
        format.js
        format.json { head :no_content }
      end
    else
      session[:reservation_step] = session[:reservation_params] = nil
      flash[:notice] = "Reservation created!"
      redirect_to @reservation
    end

  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_id %><br />
    <%= f.number_field :resource_id %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :exchange_event_id %><br />
    <%= f.text_field :exchange_event_id %>
  </div>
  <div class="field">
    <%= f.label :cache_start_time %><br />
    <%= f.datetime_select :cache_start_time %>
  </div>
  <div class="field">
    <%= f.label :cache_end_time %><br />
    <%= f.datetime_select :cache_end_time %>
  </div>
  <div class="field">
    <%= f.label :recurrence_id %><br />
    <%= f.number_field :recurrence_id %>
  </div>
  <div class="field">
    <%= f.label :questionnaire_response_id %><br />
    <%= f.number_field :questionnaire_response_id %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br />
    <%= f.number_field :package_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_step1.html.erb
<h1>Agenda</h1>

<table class="table table-striped table-condensed wizard">
  <tr>
    <th>Resource</th>
    <th>Date</th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr id="<%= 'reservation_' + reservation.id.to_s %>">
    <td><%= reservation.title %></td>
    <td><%= reservation.cache_start_time.strftime("%m/%d/%Y") %></td>
    <td><%= link_to 'Cancel', reservation, method: :delete, remote: true %></td>
  </tr>
<% end %>
</table>
<h1>What would you like to reserve?</h1>
<div class="btn-group wizard-btn-group">
	<% @resource_categories.each do |rc| %>
		<%= f.submit rc.id, :name => "resource[resource_category_id]", :class => "btn wizard-resource resource-" + rc.name %>
	<% end %>
</div>

app/views/reservations/_step2.html.erb
<p>
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
</p>
<fieldset class="dept-resource">
	<div class="control-group">
		<label class="control-label" for="input01">Department</label>
		<div class="controls">
			<%=	collection_select("resource", "ou_uid", @departments, :ou_uid, :description, { :prompt => 'Select Department', :selected => session[:resource_params]['ou_uid'].to_i } )	%>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="input01">Resource</label>
		<div class="controls">
			<select id="resource_id" name="reservation[resource_id]">
				<option value class="static">Select Resource</option>
				<% Resource.where('resource_category_id = ' + session[:resource_params]['resource_category_id']).each do |r|	%>
					<option value="<%= r.id %>"
						class="dep_<%= r.ou_uid %>"
						<% if session[:reservation_params]['resource_id'].to_i == r.id %>
						selected
						<% end %>
					>
						<%= r.name %>
					</option>
				<% end %>
			</select>
		</div>
	</div>
</fieldset>

app/views/reservations/_step3.html.erb
<p>
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
	Instructions go here. Instructions go here. Instructions go here. Instructions go here.
</p>

<%= form_for(@reservation, :remote=>true, :url => reservations_wizard_path) do |f| %>
	<%= f.fields_for :resource do |r|%>
		<%= r.fields_for :questions do |q|%>
		<fieldset>
			<div class="control-group">
				<%= q.label :question, q.object.question %>
		     	<div class="controls">
					<%= q.fields_for :question_responses do |qr|%>
						<%= qr.text_field :value, class: 'input-xlarge' %><br />
					<% end %>
		     	</div>
		   </div>
		</fieldset>
		<% end %>
	<% end %>
<% end %>

app/views/reservations/_step4.html.erb
<div id='calendar'></div>
<%= form_for(@reservation, :remote=>true, :url => reservations_wizard_path) do |f| %>
<p><%= f.submit "Back", :name => "back_button" unless @reservation.first_step? %></p>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<%= button_to "Launch Wizard", new_reservation_path, remote: true, method: :get, :update => "wizard_bootstrapper" %>
<div id="wizard_bootstrapper" />
<script type="text/javascript">
	$("form").on("ajax:complete", function(a, b) { $("div#wizard_bootstrapper").html(b.responseText); });
</script>

app/views/reservations/new.html.erb
<div class="modal hide fade" id="wizard">
	<button type="button" class="close" data-dismiss="modal">×</button>
</div>

<script id="templ-step1" type="text/template">
  	<h1>Agenda</h1>
	<div id="wizard-table">
		<table class="table table-striped table-condensed wizard">
		  <tr>
		    <th>Resource</th>
		    <th>Date</th>
		    <th></th>
		  </tr>
	
		  {{! resource_categories }}

		  {{ _.each(reservations, function(reservation) { }}
		  <tr id="reservation_{{= reservation.id }}">
		    <td> {{= reservation.id }} </td>
		    <td> {{= reservation.start }} </td>
		    <td>
				<a href="/reservations/{{= reservation.id }}" data-method="delete" data-remote="true" rel="nofollow">Cancel</a>
			</td>
		  </tr>
		  {{ }) }}
		</table>
	</div>
	<h1>What would you like to reserve?</h1>
	<div class="btn-group wizard-btn-group">
		{{ _.each(resource_categories, function(category) { }}
			<input type="submit" name="resource[{{= category.id }}]" class="btn wizard-resource resource-{{= category.name }}" >
		{{ }) }}
	</div>
</script>
<script id="tmpl-step2" type="text/template">
  	<p>{{= question.question }}</p><input type="text" />
</script>
<script id="tmpl-step3" type="text/template">
  	<p>{{= question.question }}</p><input type="text" />
</script>
<script id="tmpl-step4" type="text/template">
  	<p>{{= question.question }}</p><input type="text" />
</script>

<%= javascript_include_tag "reservations" %>
<script type="text/javascript">
	reservations.reservations = $.parseJSON('<%= @reservations.to_json.html_safe %>');
	reservations.resource_categories = $.parseJSON('<%= @resource_categories.to_json.html_safe %>');
	reservations.initialize();
</script>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Resource:</b>
  <%= @reservation.resource_id %>
</p>

<p>
  <b>Person:</b>
  <%= @reservation.person_id %>
</p>

<p>
  <b>Exchange event:</b>
  <%= @reservation.exchange_event_id %>
</p>

<p>
  <b>Cache start time:</b>
  <%= @reservation.cache_start_time %>
</p>

<p>
  <b>Cache end time:</b>
  <%= @reservation.cache_end_time %>
</p>

<p>
  <b>Recurrence:</b>
  <%= @reservation.recurrence_id %>
</p>

<p>
  <b>Questionnaire response:</b>
  <%= @reservation.questionnaire_response_id %>
</p>

<p>
  <b>Package:</b>
  <%= @reservation.package_id %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/wizard.html.erb
<%= form_for(@reservation, :remote=>true, :url => reservations_wizard_path) do |f| %>
  	<% if @reservation.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

	      <ul>
	      <% @reservation.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>
	<div id="wizard-form">
  		<%= render "#{@reservation.current_step}", :f => f %>
	</div>
	<div id="nav-area">
		<p>
		<%= f.submit "Continue", :name => "next_button", :id => "btn_continue" %>
		<%= f.submit "Back", :name => "back_button", :id => "btn_back" %>
		</p>
	</div>
<% end %>
<div id="debug-area">
	<%= debug session %>
</div>

app/views/reservations/wizard.js.erb
<% step = @reservation.current_step %>
$('div#debug-area').html("<%= escape_javascript(debug session) %>");
$('div#wizard-form').html("<%= escape_javascript(render :partial => step) %>");

step = "<%= step %>";

if ( step == "step2" ) {
	
	// Cascading select options for department resources
	// Source: http://jsatt.blogspot.com/2010/01/cascading-select-boxes-using-jquery.html
	function cascadeSelect(parent, child){
			var childOptions = child.find('option:not(.static)');
				child.data('options',childOptions);

			parent.change(function(){
				childOptions.remove();
				child
					.append(child.data('options').filter('.dep_' + this.value))
					.change();
			})

			childOptions.not('.static, .dep_' + parent.val()).remove();

	}

	$(function(){
		cascadeForm = $('.new_reservation');
		departmentSelect = cascadeForm.find('#resource_ou_uid');
		resourceSelect = cascadeForm.find('#resource_id');

		cascadeSelect(departmentSelect, resourceSelect);
	});
}
else if ( step == "step3" ){
	getResourceQuestions(<%= @resource.id if @resource %>)
}