config/routes.rb
DssScheduler::Application.routes.draw do
  resources :resources do
    resources :questions
  end
  match '/reservations/wizard', :controller => 'reservations', :action => 'wizard'
  resources :reservations
  resources :resource_categories
  
  get '/admin', :controller => "admin", :action=> "index"
  get '/welcome', :controller => "application", :action => "welcome"
  get '/logout', :controller => "application", :action => "logout"
  root :to => 'application#welcome'
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Resource Fields</h3>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :resource_category_id %><br />
	<%=collection_select(:ResourceCategory, :name, @resourceCategories, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :exchange_calendar_id %><br />
    <%= f.text_field :exchange_calendar_id %>
  </div>
  <div class="field">
    <%= f.label :ou_uid %><br />
    <%= f.number_field :ou_uid %>
  </div>
    <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_field :instructions %>
  </div>
  <div class="field">
    <%= f.label :role_required %><br />
    <%= f.check_box :role_required %>
  </div>
  <div class="field">
    <%= f.label :allow_public %><br />
    <%= f.check_box :allow_public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
    <th>Exchange calendar id</th>
    <th>Ou uid</th>
	<th>Instructions</th>
	<th>Role Required</th>
	<th>Allow Public</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.resource_category_id %></td>
    <td><%= resource.description %></td>
    <td><%= resource.exchange_calendar_id %></td>
    <td><%= resource.ou_uid %></td>
    <td><%= resource.instructions %></td>
    <td><%= resource.role_required %></td>
    <td><%= resource.allow_public %></td>
	<td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/questions.html.erb
test

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Category:</b>
  <%= @resource.resource_category_id %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>Exchange calendar id:</b>
  <%= @resource.exchange_calendar_id %>
</p>

<p>
  <b>Ou uid:</b>
  <%= @resource.ou_uid %>
</p>

<p>
  <b>Created At:</b>
  <%= @resource.created_at %>
</p>
<p>
  <b>Updated At:</b>
  <%= @resource.updated_at %>
</p>
<p>
  <b>Instructions:</b>
  <%= @resource.instructions %>
</p>
<p>
  <b>Role Required:</b>
  <%= @resource.role_required %>
</p>
<p>
  <b>Allow Public:</b>
  <%= @resource.allow_public %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>
<div id='calendar'></div>